name: SocialRadar
description: A sample Polymer application
dependencies:
  browser: any
  polymer: '>=0.15.1 <0.16.0'
  core_elements: ">=0.4.0+2 <0.5.0"
  paper_elements: ">=0.5.0 <0.6.0"
  route_hierarchical: any
transformers:
- polymer:
    entry_points: web/index.html
